name: Run Tira Scraper

on:
  workflow_dispatch:  # manual trigger

jobs:
  scrape_insurance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas playwright
          playwright install chromium

      - name: Run Python scraper
        run: |
          python scrape_env.py  # your script name

      - name: Upload CSV artifacts
        uses: actions/upload-artifact@v3
        with:
          name: processed-csv
          path: "*.csv"  # uploads all CSVs in repo/workspace
